### ISSUE TITLE
E-mail iguais 

### ISSUE THREAD

**Issue by talissonf** [ecomclub/transactional-mails#16]
Aparentemente os templates para os status `pending` e `new_order` estão idênticos https://github.com/ecomclub/app-ses/issues/13

@vitorrgg pode verificar por favor?

**Comment by leomp12** [comment]
Acredito que o e-mail de novo pedido precisa de melhorias, não é tão simples quanto um e-mail de notificação de status, inicialmente eu acho que deveria:

1. Mostrar os dois status atuais (pagamento e entrega);
2. Se o status inicial for `pending` (que é o mais comum) o e-mail **deve conter botão para finalizar pagamento** principalmente se for boleto ou tiver um link externo para pagamento;
