### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by talissonf** [ecomclub/transactional-mails#6]
https://github.com/ecomclub/transactional-mails/blob/de6041ebe4359e6691e025cfdb901fade7d4ac3b/views/new-order.ejs#L66
@vitorrgg 
When the order is created and the shipping service does not estimate the shipping time as is the case of frenet, the shipping_lines.posting_deadline object will be empty. It's good to check if it exists, if it doesn't exist use the shipping_lines.delivery_time as object.

**Comment by vitorrgg** [comment]
done
